name: employee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management:
  flutter_bloc: ^9.1.1

  # Route management:
  go_router: ^16.2.4

  # Dependency management:
  get_it: ^8.2.0

  # Location management:
  geolocator: ^14.0.2

  # Utility:
  equatable: ^2.0.7
  logger: ^2.6.2
  intl: any
  intl_utils: any
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter

  # Presentation:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  toastification: ^3.0.3
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  loading_indicator: ^3.1.1
  dropdown_button2: ^2.3.9
  flutter_week_view: ^1.4.3
  table_calendar: ^3.1.3
  sleek_circular_slider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/icon/
    - assets/image/

