name: employee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management:
  flutter_bloc: ^9.1.1

  # Route management:
  go_router: ^16.2.4

  # Presentation:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  toastification: ^3.0.3
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  loading_indicator: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/

